sudo: required
services:
    - docker

before_install:
    - docker build -t achhouy/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true achhouy/docker-react npm run test -- --coverage
